DROP TABLE IF EXISTS installs;
DROP TABLE IF EXISTS soft;
DROP TABLE IF EXISTS pcs;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS employees;

CREATE TABLE employees (id INTEGER, lname VARCHAR(20) NOT NULL, fname VARCHAR(20) NOT NULL, mname VARCHAR (20), age INTEGER NOT NULL);
CREATE TABLE rooms (id INTEGER, num INTEGER NOT NULL, emp_id INTEGER NOT NULL, appoint VARCHAR (400));
CREATE TABLE pcs (id INTEGER, room_id INTEGER NOT NULL, note VARCHAR (400), ip_addr VARCHAR(50) NOT NULL, mac_addr VARCHAR(50) NOT NULL, device_id INTEGER NOT NULL);
CREATE TABLE devices (id INTEGER, type VARCHAR(20) NOT NULL, type_con VARCHAR(20) NOT NULL);
CREATE TABLE soft (id INTEGER, sname VARCHAR(50) NOT NULL, ver VARCHAR (50) NOT NULL, quant VARCHAR (50) NOT NULL, build VARCHAR (50) NOT NULL);
CREATE TABLE installs (pc_id INTEGER, soft_id INTEGER NOT NULL, num INTEGER NOT NULL);
